import { FormEvent, useEffect, useState } from "react";
import { BriefcaseBusiness, Download, Plus, ReceiptText, Shield, WalletCards } from "lucide-react";
import { useNavigate, useSearchParams } from "react-router-dom";
import { accountMoney as money, api, pct } from "../api";
import { useAuth } from "../auth";
import LineChart from "../components/LineChart";
import { Empty, Kpi, Modal, PageHeader } from "../components/Ui";
import { useToast } from "../components/Toast";
import { Account } from "../types";

type Fill = { id: number; symbol: string; side: string; quantity: number; price: number; commission: number; stamp_duty: number; transfer_fee: number; trade_date: string; note?: string; reversal_id?: number; reversal_reason?: string };
type CashEvent = { id: number; event_type: string; amount: number; trade_date: string; note?: string; reversal_id?: number; reversal_reason?: string };
type Snapshot = { date: string; equity: number; drawdown: number };

export default function PortfolioPage() {
  const user = useAuth();
  const [params] = useSearchParams();
  const navigate = useNavigate();
  const toast = useToast();
  const [accounts, setAccounts] = useState<Account[]>([]);
  const [selected, setSelected] = useState<number | null>(params.get("account") ? +params.get("account")! : null);
  const [tab, setTab] = useState("positions");
  const [modal, setModal] = useState<"account" | "fill" | "cash" | null>(user && params.get("symbol") ? "fill" : null);
  const [fills, setFills] = useState<Fill[]>([]);
  const [cash, setCash] = useState<CashEvent[]>([]);
  const [snapshots, setSnapshots] = useState<Snapshot[]>([]);
  const load = () => api<Account[]>("/accounts").then((rows) => { setAccounts(rows); if (!selected && rows[0]) setSelected(rows[0].id); }).catch((e) => toast.show(e.message, "error"));
  useEffect(() => { void load(); }, []);
  useEffect(() => { if (!selected) return; Promise.all([api<Fill[]>(`/accounts/${selected}/fills`), api<CashEvent[]>(`/accounts/${selected}/cash-events`), api<Snapshot[]>(`/accounts/${selected}/snapshots`)]).then(([a, b, c]) => { setFills(a); setCash(b); setSnapshots(c); }); }, [selected, accounts]);
  const account = accounts.find((item) => item.id === selected);
  const refresh = () => { load(); if (selected) Promise.all([api<Fill[]>(`/accounts/${selected}/fills`), api<CashEvent[]>(`/accounts/${selected}/cash-events`), api<Snapshot[]>(`/accounts/${selected}/snapshots`)]).then(([a, b, c]) => { setFills(a); setCash(b); setSnapshots(c); }); };
  const reverse = async (kind: "fills" | "cash-events", id: number) => { const reason = window.prompt("请输入冲正原因（原记录将永久保留）："); if (!reason) return; try { await api(`/accounts/${selected}/${kind}/${id}/reverse`, { method: "POST", body: JSON.stringify({ reason }) }); toast.show("冲正完成，原记录已保留"); refresh(); } catch (e) { toast.show((e as Error).message, "error"); } };
  const setRisk = async (symbol: string, current?: number) => { const value = window.prompt(`设置 ${symbol} 止损价：`, current ? String(current) : ""); if (!value || !account) return; await api(`/accounts/${account.id}/positions/${symbol}/risk`, { method: "PUT", body: JSON.stringify({ stop_price: +value, note: "人工持仓风控" }) }); toast.show("持仓止损已更新"); refresh(); };
  return <>
    <PageHeader title="组合账户" subtitle="模拟账户严格校验交易规则，实盘账本忠实记录并对异常提示" actions={user ? <><button className="secondary icon-button" onClick={() => setModal("account")}><Plus size={15} />新建账户</button>{account && <><button className="secondary icon-button" onClick={() => setModal("cash")}><WalletCards size={15} />资金流水</button><button className="primary icon-button" onClick={() => setModal("fill")}><ReceiptText size={15} />录入成交</button></>}</> : undefined} />
    {accounts.length === 0 ? <Empty>{user ? "尚未创建组合，请先创建一个模拟组合。" : "登录或注册后可创建个人模拟组合并开始模拟交易。"}</Empty> : <>
      <div className="account-tabs">{accounts.map((item) => <button key={item.id} className={selected === item.id ? "active" : ""} onClick={() => setSelected(item.id)}><span>{item.account_type === "PAPER" ? "模拟" : "实盘"}</span>{item.name}</button>)}</div>
      {account && <>
        <section className="kpi-grid compact"><Kpi label="账户权益" value={`¥ ${money(account.portfolio.equity)}`} /><Kpi label="可用现金" value={`¥ ${money(account.portfolio.cash)}`} tone="green" /><Kpi label="总仓位" value={pct(account.portfolio.total_weight)} tone="orange" note="上限 60%" /><Kpi label="累计盈亏" value={`¥ ${money(account.portfolio.realized_pnl + account.portfolio.unrealized_pnl)}`} tone={account.portfolio.realized_pnl + account.portfolio.unrealized_pnl >= 0 ? "green" : "red"} /></section>
        <div className="content-tabs"><button className={tab === "positions" ? "active" : ""} onClick={() => setTab("positions")}><BriefcaseBusiness size={15} />持仓</button><button className={tab === "fills" ? "active" : ""} onClick={() => setTab("fills")}><ReceiptText size={15} />成交</button><button className={tab === "cash" ? "active" : ""} onClick={() => setTab("cash")}><WalletCards size={15} />资金</button><button className={tab === "risk" ? "active" : ""} onClick={() => setTab("risk")}><Shield size={15} />风险与权益</button></div>
        {tab === "positions" && <Positions account={account} navigate={navigate} onRisk={user ? setRisk : undefined} />}
        {tab === "fills" && <Fills rows={fills} accountId={account.id} onReverse={user ? (id) => reverse("fills", id) : undefined} />}
        {tab === "cash" && <CashEvents rows={cash} accountId={account.id} onReverse={user ? (id) => reverse("cash-events", id) : undefined} />}
        {tab === "risk" && <RiskView account={account} rows={snapshots} />}
      </>}
    </>}
    {user && modal === "account" && <Modal title="新建交易账户" onClose={() => setModal(null)}><AccountForm onSaved={() => { setModal(null); refresh(); }} /></Modal>}
    {user && modal === "fill" && account && <Modal title={`录入成交 · ${account.name}`} onClose={() => setModal(null)}><FillForm account={account} initialSymbol={params.get("symbol") || ""} initialPrice={+(params.get("price") || 0)} onSaved={() => { setModal(null); refresh(); }} /></Modal>}
    {user && modal === "cash" && account && <Modal title={`资金流水 · ${account.name}`} onClose={() => setModal(null)}><CashForm account={account} onSaved={() => { setModal(null); refresh(); }} /></Modal>}
  </>;
}

function Positions({ account, navigate, onRisk }: { account: Account; navigate: ReturnType<typeof useNavigate>; onRisk?: (symbol: string, stop?: number) => void }) { const p = account.portfolio; return <section className="table-panel">{p.positions.length === 0 ? <Empty>当前没有持仓。</Empty> : <div className="table-scroll"><table><thead><tr><th>标的</th><th>数量</th><th>平均成本</th><th>最新价</th><th>市值 / 仓位</th><th>浮动盈亏</th><th>止损 / 距离</th><th>风险金额</th><th>行情日</th></tr></thead><tbody>{p.positions.map((row) => <tr key={row.symbol}><td className="click-cell" onClick={() => navigate(`/stocks/${row.symbol}`)}><b>{row.symbol}</b></td><td>{row.quantity}</td><td>{money(row.average_cost)}</td><td>{money(row.last_price)}</td><td>¥ {money(row.market_value)}<small>{pct(row.market_value / p.equity)}</small></td><td className={row.unrealized_pnl >= 0 ? "positive" : "negative"}>¥ {money(row.unrealized_pnl)}<small>{pct(row.return_pct)}</small></td><td>{onRisk ? <button className="text-button" onClick={() => onRisk(row.symbol, row.stop_price)}>{money(row.stop_price) || "设置止损"}</button> : <span>{money(row.stop_price)}</span>}<small className={(row.stop_distance || 1) <= .03 ? "negative" : ""}>{pct(row.stop_distance)}</small></td><td>{money(row.risk_amount)}</td><td>{row.quote_date || "—"}</td></tr>)}</tbody></table></div>}</section>; }

function Fills({ rows, accountId, onReverse }: { rows: Fill[]; accountId: number; onReverse?: (id: number) => void }) { return <section className="table-panel"><div className="panel-title"><div><h2>成交记录</h2><small>移动加权平均成本 · 原记录不可删除</small></div><a className="secondary icon-button" href={`/api/v1/accounts/${accountId}/export/fills.csv`}><Download size={15} />导出 CSV</a></div>{rows.length === 0 ? <Empty>暂无成交记录。</Empty> : <div className="table-scroll"><table><thead><tr><th>日期</th><th>代码</th><th>方向</th><th>数量</th><th>价格</th><th>费用</th><th>备注</th><th>状态</th>{onReverse && <th>操作</th>}</tr></thead><tbody>{rows.map((row) => <tr key={row.id} className={row.reversal_id ? "reversed-row" : ""}><td>{row.trade_date}</td><td>{row.symbol}</td><td className={row.side === "BUY" ? "positive" : "negative"}>{row.side}</td><td>{row.quantity}</td><td>{money(row.price)}</td><td>{money(row.commission + row.stamp_duty + row.transfer_fee)}</td><td>{row.reversal_reason || row.note || "—"}</td><td>{row.reversal_id ? <span className="status failed">已冲正</span> : <span className="status succeeded">有效</span>}</td>{onReverse && <td><button className="text-button danger-text" disabled={Boolean(row.reversal_id)} onClick={() => onReverse(row.id)}>冲正</button></td>}</tr>)}</tbody></table></div>}</section>; }

function CashEvents({ rows, accountId, onReverse }: { rows: CashEvent[]; accountId: number; onReverse?: (id: number) => void }) { return <section className="table-panel"><div className="panel-title"><div><h2>资金流水</h2><small>出入金、分红、费用与人工调整</small></div><a className="secondary icon-button" href={`/api/v1/accounts/${accountId}/export/cash.csv`}><Download size={15} />导出 CSV</a></div>{rows.length === 0 ? <Empty>暂无资金流水。</Empty> : <div className="table-scroll"><table><thead><tr><th>日期</th><th>类型</th><th>金额</th><th>备注</th><th>状态</th>{onReverse && <th>操作</th>}</tr></thead><tbody>{rows.map((row) => <tr key={row.id} className={row.reversal_id ? "reversed-row" : ""}><td>{row.trade_date}</td><td>{row.event_type}</td><td className={row.amount >= 0 ? "positive" : "negative"}>¥ {money(row.amount)}</td><td>{row.reversal_reason || row.note || "—"}</td><td>{row.reversal_id ? <span className="status failed">已冲正</span> : <span className="status succeeded">有效</span>}</td>{onReverse && <td><button className="text-button danger-text" disabled={Boolean(row.reversal_id)} onClick={() => onReverse(row.id)}>冲正</button></td>}</tr>)}</tbody></table></div>}</section>; }

function RiskView({ account, rows }: { account: Account; rows: Snapshot[] }) { const maxDrawdown = Math.min(0, ...rows.map((row) => row.drawdown)); return <><section className="panel"><div className="panel-title"><div><h2>账户权益曲线</h2><small>从工作台上线日开始真实记录，不伪造历史快照</small></div><span className="negative">最大回撤 {pct(maxDrawdown)}</span></div>{rows.length ? <LineChart rows={rows} /> : <Empty>完成一次账本操作或日跑后开始记录权益快照。</Empty>}</section><section className="risk-cards"><div><span>单笔亏损预算</span><b>¥ {money(account.portfolio.equity * .01)}</b><small>账户权益 1%</small></div><div><span>单票市值上限</span><b>¥ {money(account.portfolio.equity * .2)}</b><small>账户权益 20%</small></div><div><span>总仓位上限</span><b>¥ {money(account.portfolio.equity * .6)}</b><small>账户权益 60%</small></div><div><span>剩余持仓槽位</span><b>{Math.max(0, 5 - account.portfolio.positions.length)}</b><small>最多同时 5 只</small></div></section></>; }

function AccountForm({ onSaved }: { onSaved: () => void }) { const user = useAuth(); const toast = useToast(); const [form, setForm] = useState({ name: "模拟组合", account_type: "PAPER", initial_cash: 1000000, commission_rate: 0.0003, minimum_commission: 5, stamp_duty_rate: 0.0005, transfer_fee_rate: 0.00001 }); const submit = async (e: FormEvent) => { e.preventDefault(); try { await api("/accounts", { method: "POST", body: JSON.stringify(form) }); toast.show("账户已创建"); onSaved(); } catch (reason) { toast.show((reason as Error).message, "error"); } }; return <form className="stack-form" onSubmit={submit}><div className="form-row"><label>账户名称<input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><label>类型<select value={form.account_type} disabled={user?.role !== "ADMIN"} onChange={(e) => setForm({ ...form, account_type: e.target.value })}><option value="PAPER">模拟组合</option>{user?.role === "ADMIN" && <option value="REAL_LEDGER">人工实盘账本</option>}</select></label></div><label>初始资金<input type="number" value={form.initial_cash} onChange={(e) => setForm({ ...form, initial_cash: +e.target.value })} /></label><div className="form-row"><label>佣金率<input type="number" step="0.00001" value={form.commission_rate} onChange={(e) => setForm({ ...form, commission_rate: +e.target.value })} /></label><label>最低佣金<input type="number" step="0.01" value={form.minimum_commission} onChange={(e) => setForm({ ...form, minimum_commission: +e.target.value })} /></label></div><div className="form-row"><label>卖出印花税率<input type="number" step="0.00001" value={form.stamp_duty_rate} onChange={(e) => setForm({ ...form, stamp_duty_rate: +e.target.value })} /></label><label>过户费率<input type="number" step="0.00001" value={form.transfer_fee_rate} onChange={(e) => setForm({ ...form, transfer_fee_rate: +e.target.value })} /></label></div><div className="warning-banner">{user?.role === "ADMIN" ? "请按券商合同确认费率，系统不会替您假定真实费率。" : "个人账号创建的组合仅用于模拟交易，数据只归当前账号所有。"}</div><button className="primary">确认并创建</button></form>; }

function FillForm({ account, initialSymbol, initialPrice, onSaved }: { account: Account; initialSymbol: string; initialPrice: number; onSaved: () => void }) { const toast = useToast(); const [form, setForm] = useState({ symbol: initialSymbol, side: "BUY", quantity: 100, price: initialPrice, trade_date: new Date().toISOString().slice(0, 10), note: "" }); const submit = async (e: FormEvent) => { e.preventDefault(); try { const result = await api<{ warnings: string[] }>(`/accounts/${account.id}/fills`, { method: "POST", body: JSON.stringify(form) }); toast.show(result.warnings?.join("；") || "成交已保存"); onSaved(); } catch (reason) { toast.show((reason as Error).message, "error"); } }; const paperBuy = form.side === "BUY" && account.account_type === "PAPER"; return <form className="stack-form" onSubmit={submit}><div className="form-row"><label>股票代码<input pattern="\d{6}" value={form.symbol} onChange={(e) => setForm({ ...form, symbol: e.target.value })} /></label><label>方向<select value={form.side} onChange={(e) => setForm({ ...form, side: e.target.value })}><option value="BUY">买入</option><option value="SELL">卖出</option></select></label></div><div className="form-row"><label>数量<input type="number" min={paperBuy ? 100 : 1} step={paperBuy ? 100 : 1} value={form.quantity} onChange={(e) => setForm({ ...form, quantity: +e.target.value })} /></label><label>成交价<input type="number" min="0.01" step="0.01" value={form.price} onChange={(e) => setForm({ ...form, price: +e.target.value })} /></label></div><label>成交日期<input type="date" value={form.trade_date} onChange={(e) => setForm({ ...form, trade_date: e.target.value })} /></label><label>备注<textarea value={form.note} onChange={(e) => setForm({ ...form, note: e.target.value })} /></label><button className="primary">保存成交</button></form>; }

function CashForm({ account, onSaved }: { account: Account; onSaved: () => void }) { const toast = useToast(); const [form, setForm] = useState({ event_type: "DEPOSIT", amount: 0, trade_date: new Date().toISOString().slice(0, 10), note: "" }); const submit = async (e: FormEvent) => { e.preventDefault(); try { await api(`/accounts/${account.id}/cash-events`, { method: "POST", body: JSON.stringify(form) }); toast.show("资金流水已保存"); onSaved(); } catch (reason) { toast.show((reason as Error).message, "error"); } }; return <form className="stack-form" onSubmit={submit}><div className="form-row"><label>类型<select value={form.event_type} onChange={(e) => setForm({ ...form, event_type: e.target.value })}><option value="DEPOSIT">入金</option><option value="WITHDRAWAL">出金</option><option value="DIVIDEND">分红</option><option value="FEE">费用</option><option value="ADJUSTMENT">人工调整</option></select></label><label>金额<input type="number" step="0.01" value={form.amount} onChange={(e) => setForm({ ...form, amount: +e.target.value })} /></label></div><label>日期<input type="date" value={form.trade_date} onChange={(e) => setForm({ ...form, trade_date: e.target.value })} /></label><label>备注<textarea value={form.note} onChange={(e) => setForm({ ...form, note: e.target.value })} /></label><button className="primary">保存流水</button></form>; }
