import { FormEvent, useEffect, useState } from "react";
import { api, money, pct } from "../api";
import { Empty, Kpi, PageHeader } from "../components/Ui";
import { Account } from "../types";

export default function PortfolioPage() {
  const [accounts, setAccounts] = useState<Account[]>([]); const [selected, setSelected] = useState<number | null>(null); const [showCreate, setShowCreate] = useState(false); const [showFill, setShowFill] = useState(false); const [error, setError] = useState("");
  const load = () => api<Account[]>("/accounts").then((rows) => { setAccounts(rows); if (!selected && rows[0]) setSelected(rows[0].id); }).catch((e) => setError(e.message));
  useEffect(() => { void load(); }, []);
  const account = accounts.find((item) => item.id === selected);
  return <><PageHeader title="组合与成交" subtitle="模拟组合严格执行 A 股交易规则，实盘账本忠实记录人工成交" actions={<><button className="secondary" onClick={() => setShowCreate(true)}>＋ 新建账户</button>{account && <button className="primary" onClick={() => setShowFill(true)}>录入成交</button>}</>} />{error && <div className="error-box">{error}</div>}{accounts.length === 0 ? <Empty>尚未创建账户。创建时需要确认佣金、最低佣金、印花税与过户费。</Empty> : <><div className="account-tabs">{accounts.map((item) => <button key={item.id} className={selected === item.id ? "active" : ""} onClick={() => setSelected(item.id)}><span>{item.account_type === "PAPER" ? "模拟" : "实盘"}</span>{item.name}</button>)}</div>{account && <AccountView account={account} />}</>}{showCreate && <Modal title="新建交易账户" onClose={() => setShowCreate(false)}><AccountForm onSaved={() => { setShowCreate(false); load(); }} /></Modal>}{showFill && account && <Modal title={`录入成交 · ${account.name}`} onClose={() => setShowFill(false)}><FillForm account={account} onSaved={() => { setShowFill(false); load(); }} /></Modal>}</>;
}

function AccountView({ account }: { account: Account }) { const p = account.portfolio; return <><section className="kpi-grid compact"><Kpi label="账户权益" value={`¥ ${money(p.equity)}`} /><Kpi label="可用现金" value={`¥ ${money(p.cash)}`} tone="green" /><Kpi label="总仓位" value={pct(p.total_weight)} tone="orange" /><Kpi label="总盈亏" value={`¥ ${money(p.realized_pnl + p.unrealized_pnl)}`} tone={p.realized_pnl + p.unrealized_pnl >= 0 ? "green" : "red"} /></section><section className="table-panel"><div className="panel-title"><div><h2>当前持仓</h2><small>{p.positions.length}/5 只 · 上限 60%</small></div></div>{p.positions.length === 0 ? <Empty>当前没有持仓，候选交易计划可在录入成交时关联。</Empty> : <div className="table-scroll"><table><thead><tr><th>代码</th><th>数量</th><th>平均成本</th><th>最新价</th><th>市值</th><th>仓位</th><th>浮动盈亏</th><th>收益率</th><th>行情日</th></tr></thead><tbody>{p.positions.map((row) => <tr key={row.symbol}><td><b>{row.symbol}</b></td><td>{row.quantity}</td><td>{money(row.average_cost)}</td><td>{money(row.last_price)}</td><td>¥ {money(row.market_value)}</td><td>{pct(row.market_value / p.equity)}</td><td className={row.unrealized_pnl >= 0 ? "positive" : "negative"}>¥ {money(row.unrealized_pnl)}</td><td className={row.return_pct >= 0 ? "positive" : "negative"}>{pct(row.return_pct)}</td><td>{row.quote_date || "—"}</td></tr>)}</tbody></table></div>}</section></>; }

function Modal({ title, onClose, children }: { title: string; onClose: () => void; children: React.ReactNode }) { return <div className="drawer-backdrop" onMouseDown={onClose}><div className="modal" onMouseDown={(e) => e.stopPropagation()}><button className="drawer-close" onClick={onClose}>×</button><h2>{title}</h2>{children}</div></div>; }

function AccountForm({ onSaved }: { onSaved: () => void }) { const [form, setForm] = useState({ name: "模拟组合", account_type: "PAPER", initial_cash: 1000000, commission_rate: 0.0003, minimum_commission: 5, stamp_duty_rate: 0.0005, transfer_fee_rate: 0.00001 }); const [error, setError] = useState(""); const submit = async (e: FormEvent) => { e.preventDefault(); try { await api("/accounts", { method: "POST", body: JSON.stringify(form) }); onSaved(); } catch (reason) { setError((reason as Error).message); } }; const set = (key: string, value: string | number) => setForm({ ...form, [key]: value }); return <form className="stack-form" onSubmit={submit}><div className="form-row"><label>账户名称<input value={form.name} onChange={(e) => set("name", e.target.value)} /></label><label>类型<select value={form.account_type} onChange={(e) => set("account_type", e.target.value)}><option value="PAPER">模拟组合</option><option value="REAL_LEDGER">人工实盘账本</option></select></label></div><label>初始资金<input type="number" value={form.initial_cash} onChange={(e) => set("initial_cash", +e.target.value)} /></label><div className="form-row"><label>佣金率<input type="number" step="0.00001" value={form.commission_rate} onChange={(e) => set("commission_rate", +e.target.value)} /></label><label>最低佣金<input type="number" step="0.01" value={form.minimum_commission} onChange={(e) => set("minimum_commission", +e.target.value)} /></label></div><div className="form-row"><label>卖出印花税率<input type="number" step="0.00001" value={form.stamp_duty_rate} onChange={(e) => set("stamp_duty_rate", +e.target.value)} /></label><label>过户费率<input type="number" step="0.00001" value={form.transfer_fee_rate} onChange={(e) => set("transfer_fee_rate", +e.target.value)} /></label></div><div className="warning-banner">费率只是初始示例，请按您的券商合同确认后再创建。</div>{error && <div className="error-box">{error}</div>}<button className="primary">确认并创建</button></form>; }

function FillForm({ account, onSaved }: { account: Account; onSaved: () => void }) { const [form, setForm] = useState({ symbol: "", side: "BUY", quantity: 100, price: 0, trade_date: new Date().toISOString().slice(0, 10), note: "" }); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const set = (key: string, value: string | number) => setForm({ ...form, [key]: value }); const submit = async (e: FormEvent) => { e.preventDefault(); try { const result = await api<{ warnings: string[] }>(`/accounts/${account.id}/fills`, { method: "POST", body: JSON.stringify(form) }); if (result.warnings.length) { setMessage(result.warnings.join("；")); setTimeout(onSaved, 1200); } else onSaved(); } catch (reason) { setError((reason as Error).message); } }; return <form className="stack-form" onSubmit={submit}><div className="form-row"><label>股票代码<input pattern="\d{6}" value={form.symbol} onChange={(e) => set("symbol", e.target.value)} placeholder="600519" /></label><label>方向<select value={form.side} onChange={(e) => set("side", e.target.value)}><option value="BUY">买入</option><option value="SELL">卖出</option></select></label></div><div className="form-row"><label>数量<input type="number" min="1" step={form.side === "BUY" ? 100 : 1} value={form.quantity} onChange={(e) => set("quantity", +e.target.value)} /></label><label>成交价<input type="number" min="0.01" step="0.01" value={form.price} onChange={(e) => set("price", +e.target.value)} /></label></div><label>成交日期<input type="date" value={form.trade_date} onChange={(e) => set("trade_date", e.target.value)} /></label><label>备注<textarea value={form.note} onChange={(e) => set("note", e.target.value)} /></label>{error && <div className="error-box">{error}</div>}{message && <div className="warning-banner">{message}</div>}<button className="primary">保存成交</button></form>; }
