import { useEffect, useState } from "react";
import { ArrowLeft, ArrowRight, BarChart3, Printer } from "lucide-react";
import { useNavigate, useParams } from "react-router-dom";
import { api, pct } from "../api";
import { confidenceLabel, Empty, PageHeader, StatusBadge, ZoneBadge } from "../components/Ui";
import { strategyLabel } from "../strategies";

type Report = { id: number; trade_date: string; title: string; created_at: string; summary: { candidate_count: number; eligible_count: number; action: string; zone_counts: Record<string, number> } };
type Detail = Report & { candidates: Array<{ id: number; symbol: string; name?: string; industry?: string; total_score: number; confidence: string; consensus_count: number; current_zone: string; plan_status: string; return_1d?: number; return_5d?: number; return_20d?: number; mfe?: number; mae?: number; hit_entry: number; hit_stop: number }> };
type Analytics = { label: string; count: number; avg_1d?: number; avg_5d?: number; avg_20d?: number; avg_mfe?: number; avg_mae?: number; entry_rate?: number; stop_rate?: number; win_rate?: number };

const zoneLabels: Record<string, string> = { LEFT: "左侧", MIDDLE: "中部", RIGHT: "右侧", VETO: "否决" };

function analyticsLabel(group: string, label: string) {
  if (group === "strategy") return strategyLabel(label);
  if (group === "zone") return zoneLabels[label] || label;
  if (group === "confidence") return confidenceLabel(label);
  return label || "未分类";
}

export default function Reports() { const { reportId } = useParams(); return reportId ? <ReportDetail reportId={+reportId} /> : <ReportList />; }

function ReportList() { const [rows, setRows] = useState<Report[]>([]); const [analytics, setAnalytics] = useState<Analytics[]>([]); const [group, setGroup] = useState("zone"); const navigate = useNavigate(); useEffect(() => { api<Report[]>("/reports").then(setRows); }, []); useEffect(() => { api<Analytics[]>(`/analytics/candidates?group_by=${group}`).then(setAnalytics); }, [group]); return <><PageHeader title="复盘分析" subtitle="日报归档与信号后表现统计，验证策略而不是只看当天结果" actions={<select value={group} onChange={(e) => setGroup(e.target.value)}><option value="zone">按位置统计</option><option value="strategy">按策略统计</option><option value="score">按分数统计</option><option value="confidence">按置信度统计</option></select>} /><section className="table-panel"><div className="panel-title"><div><BarChart3 size={17} /><h2>候选表现统计</h2><small>基于已产生后续行情的信号</small></div></div>{analytics.length === 0 ? <Empty>尚无足够的后续表现数据。</Empty> : <div className="table-scroll"><table><thead><tr><th>分组</th><th>样本</th><th>1 日</th><th>5 日</th><th>20 日</th><th>胜率</th><th>MFE</th><th>MAE</th><th>买入区触发</th><th>止损触发</th></tr></thead><tbody>{analytics.map((row) => <tr key={row.label}><td><b>{analyticsLabel(group, row.label)}</b>{group === "strategy" && <small>{row.label}</small>}</td><td>{row.count}</td><td className={(row.avg_1d || 0) >= 0 ? "positive" : "negative"}>{pct(row.avg_1d)}</td><td className={(row.avg_5d || 0) >= 0 ? "positive" : "negative"}>{pct(row.avg_5d)}</td><td className={(row.avg_20d || 0) >= 0 ? "positive" : "negative"}>{pct(row.avg_20d)}</td><td>{pct(row.win_rate)}</td><td className="positive">{pct(row.avg_mfe)}</td><td className="negative">{pct(row.avg_mae)}</td><td>{pct(row.entry_rate)}</td><td>{pct(row.stop_rate)}</td></tr>)}</tbody></table></div>}</section><section className="report-grid">{rows.length === 0 ? <Empty>暂无日报，完成一次日常跑数后会自动生成。</Empty> : rows.map((row) => <button className="report-card" key={row.id} onClick={() => navigate(`/reports/${row.id}`)}><div className="report-date"><b>{row.trade_date.slice(8, 10)}</b><span>{row.trade_date.slice(0, 7)}</span></div><div><span className="eyebrow">DAILY BRIEF</span><h3>{row.title}</h3><p>{row.summary.action}</p><div className="report-tags"><span>{row.summary.candidate_count} 只候选</span><span>{row.summary.eligible_count} 只可执行</span><span>{row.summary.zone_counts.VETO || 0} 只否决</span></div></div><ArrowRight size={18} /></button>)}</section></>; }

function ReportDetail({ reportId }: { reportId: number }) { const [row, setRow] = useState<Detail | null>(null); const navigate = useNavigate(); useEffect(() => { api<Detail>(`/reports/${reportId}`).then(setRow); }, [reportId]); if (!row) return <div className="skeleton">正在打开复盘日报…</div>; return <><button className="back-link" onClick={() => navigate("/reports")}><ArrowLeft size={15} />返回日报列表</button><PageHeader title={row.title} subtitle={`${row.trade_date} · ${row.summary.action}`} actions={<a className="secondary icon-button" href={`/api/v1/reports/${row.id}/html`} target="_blank" rel="noreferrer"><Printer size={15} />打印版</a>} /><section className="kpi-grid"><div className="kpi"><span>候选数</span><strong>{row.summary.candidate_count}</strong></div><div className="kpi green"><span>可执行</span><strong>{row.summary.eligible_count}</strong></div><div className="kpi orange"><span>左侧 / 中部</span><strong>{row.summary.zone_counts.LEFT || 0} / {row.summary.zone_counts.MIDDLE || 0}</strong></div><div className="kpi red"><span>右侧 / 否决</span><strong>{row.summary.zone_counts.RIGHT || 0} / {row.summary.zone_counts.VETO || 0}</strong></div></section><section className="table-panel"><div className="panel-title"><div><h2>当日候选快照与后续表现</h2><small>数据会随新的交易日持续补全</small></div></div><div className="table-scroll"><table><thead><tr><th>标的</th><th>行业</th><th>分数 / 共振</th><th>位置</th><th>计划</th><th>1 日</th><th>5 日</th><th>20 日</th><th>MFE / MAE</th><th>事件</th></tr></thead><tbody>{row.candidates.map((item) => <tr key={item.id} className="click-row" onClick={() => navigate(`/stocks/${item.symbol}`)}><td><b>{item.name || item.symbol}</b><small>{item.symbol}</small></td><td>{item.industry || "—"}</td><td>{item.total_score}/8<small>{item.consensus_count} 个策略 · {confidenceLabel(item.confidence)}</small></td><td><ZoneBadge zone={item.current_zone} /></td><td><StatusBadge status={item.plan_status} /></td><td>{pct(item.return_1d)}</td><td>{pct(item.return_5d)}</td><td>{pct(item.return_20d)}</td><td><span className="positive">{pct(item.mfe)}</span> / <span className="negative">{pct(item.mae)}</span></td><td>{item.hit_entry ? "触及买入区" : "—"}{item.hit_stop ? " · 触发止损" : ""}</td></tr>)}</tbody></table></div></section></>; }
